language: node_js
node_js:
  - '0.10'

script: grunt test 

before_script:
#- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- 'npm install -d'
- 'npm install -g grunt-cli'
- sleep 3



